### ISSUE TITLE
Is the github up to date with the latest release versions of opsgenie? 

### ISSUE THREAD

**Issue by tariq1890** [opsgenie/opsgenieclient#11]
I am asking to make sure I fork the right version of opsgenie sdk. I see that current release version is 2.11.0 while the github version is at 2.0.1-SNAPSHOT.

Since we are using version 2.9.0, we'd like to fork that code and migrate to jersey v2 . ( Issue #10)

**Comment by tariq1890** [comment]
@alpgurtan Any update on this?

**Comment by davidkarlsen** [comment]
Any progress here?

**Comment by halitokumus** [comment]
Do you mean the Java SDK? Java SDK should be at 2.10.0 currently, where do you see the 2.0.1-SNAPSHOT?

**Comment by omerozkan** [comment]
Hello,
We are using a different release strategy. All the SDK and client tools' versions are defined in https://github.com/opsgenie/opsgenie-integration/blob/master/version.properties file. You can see the line:

`sdk=2.10.0` is the latest version of the java sdk.
