### ISSUE TITLE
FIle descriptor leaks.

### ISSUE THREAD

**Issue by metabsd** [opsgenie/opsgenieclient#9]
Hi,

I use Marid plugin with Nagios XI Integration for opsgenie. I see a lot of java process. Can you help me to fix that please.

16/12/30 05:03:38.968 WARN: AsyncHttpClient.close() hasn't been invoked, which may produce file descriptor leaks
16/12/30 05:03:38.971 WARN: AsyncHttpClient.close() hasn't been invoked, which may produce file descriptor leaks
16/12/30 05:03:38.971 WARN: AsyncHttpClient.close() hasn't been invoked, which may produce file descriptor leaks

I already speak with a Support member on opsgenie.com

**Comment by halitokumus** [comment]
We investigated, it's caused by a bug in Pubnub library. We'll look into updating the library.
